### ISSUE TITLE
getAlternativePromoters (Bioconductor version dont have it)

### ISSUE THREAD

**Issue by ashokpatowary** [GoekeLab/proActiv#26]
Hi 

I am interested in `getAlternativePromoters` in my dataset. The bioconductor version is not having this function; so I installed from github. However, while running I cant see any alternative promoter. I have relaxed the condition to `promoterFC=0.1, geneFC=10, maxPval=0.9`; then also no results. 

Does, `getAlternativePromoters` need replicates to call it?

Thanks

**Comment by jleechung** [comment]
Hi @ashokpatowary thank you for your interest in proActiv! The version of proActiv with the latest release of Bioconductor (3.13) should have this function implemented. Of course you can also install the development version for latest updates. Would you mind posting this question to the Bioconductor forum? https://support.bioconductor.org/ We will respond there so others can easily find this.
