### ISSUE TITLE
Docker image for proActiv

### ISSUE THREAD

**Issue by NaotoKubota** [GoekeLab/proActiv#32]
I wrote a Dockerfile for proActiv, maybe it is helpful

[https://hub.docker.com/r/naotokubota/proactiv](https://hub.docker.com/r/naotokubota/proactiv)

**Comment by jonathangoeke** [comment]
Thanks @NaotoKubota! Biocontainers also provides containers for Bioconductor packages like proActiv (https://biocontainers.pro/tools/bioconductor-proactiv), but not for all versions (and not for the one that you created)

**Comment by NaotoKubota** [comment]
I didn't know that! It seems to be very useful, thank you very much:)
