### ISSUE TITLE
used for 10x data

### ISSUE THREAD

**Issue by houruiyan** [GoekeLab/proActiv#40]
Dear Dr. I found a ppt from you in 2021 BioC. You display the proActiv applying in smart-seq2 data. Any suggestion to deal with smart-seq2 data? In addition, I want to use your package in 10x. I used the pseudo bulk. However, even if I relex the threshold , it still cannot detect any alternative promoter? Any suggestion? Thank you very much!

**Comment by houruiyan** [comment]
Here, how do you did the preprocessing (i.e. filtering)?  Thank you!
<img width="582" alt="image" src="https://user-images.githubusercontent.com/56068158/164390039-76151be8-7fd6-4bcb-ab74-9bc5739fe955.png">

**Comment by jleechung** [comment]
Hi @houruiyan 

For filtering we adopted a standard approach:

- Filtered out cells expressing less than a certain number of genes
- Filtered out genes expressed in less than a certain number of cells

You can try to tweak these thresholds and see how it affects the results.

We've only tried proActiv on full-length single cell sequencing protocols (like SMART-seq). We surmise it might be difficult to get results from 10X 3' data as there are fewer junction reads toward the 5' end.
