### ISSUE TITLE
What is the mean of names(genomeStyles()) ? 

### ISSUE THREAD

**Issue by houruiyan** [GoekeLab/proActiv#49]
Hi , Thank you very much for this greate package. 

I want to  use it to detect the promoter activity in chicken. However, when I do annotation, there is an error as following.

```
library(proActiv)
## From GTF file path
gtf.file <- '/mnt/ruiyanhou/nfs_share2/RNA_seq_organ_species/chicken/ref_files/galGal4.ensGene.gtf'

promoterAnnotation.gencode.v34.subset <- preparePromoterAnnotation(file = gtf.file,
                                                                   species = 'Gallus_gallus')
```
![image](https://github.com/GoekeLab/proActiv/assets/56068158/a328f81f-53e1-42bc-bc74-ad74a00bdebb)

I don't know the reason. Do your package support any species? 

I found the illustration about the species. 
![image](https://github.com/GoekeLab/proActiv/assets/56068158/1480f07d-f845-4d44-bb0e-2e07ad3827db)
![image](https://github.com/GoekeLab/proActiv/assets/56068158/7db2617a-91c6-4627-a82b-1c25bdb8e7dc)

So your package just support these species mentioned above? 

Hope to get your reply.

Thank you in advance!

**Comment by jleechung** [comment]
Hi @houruiyan, `proActiv` should work for the species specified above. For non-standard species some preprocessing of the gene annotations may be necessary but this varies on a case-by-case basis. Please see #48 as an example.

**Comment by houruiyan** [comment]
Thank you! Now it solved!
