### ISSUE TITLE
Couldn't find a BSgenome data package that matches genome assembly: oryCun2.0

### ISSUE THREAD

**Issue by houruiyan** [GoekeLab/proActiv#51]
Hi Dr,

I wonder if your package can work on species who did not corresponsding BSgenome data package. 

I want to use the proActiv on rabbit, however, there is not a rabbit BSgenome data package. So I don't know how to do that. Could you help me? Thank you

```
rabbit.gtf.file <- '/mnt/ruiyanhou/nfs_share2/RNA_seq_organ_species/ref_annotation/Oryctolagus_cuniculus.OryCun2.0.77.gtf.gz'
rabbit_annotation <- preparePromoterAnnotation(file = rabbit.gtf.file, species = 'Oryctolagus_cuniculus')
  rabbit_result <- proActiv(files = allfiles,
                           promoterAnnotation = rabbit_annotation,
                           genome='oryCun2.0',
                           ncores=1,
                           condition = condition)
```

Can I create a BSgenome data package for rabbit? But how proActiv can identify that? 

Hope to get your reply! 

Best regards,
Ruiyan

**Comment by jleechung** [comment]
I guess you are passing bam files to `proActiv`? Assuming you have the raw reads, one option is to use the junction files returned by your aligner directly (for example, the `SJ.out.tab` files for STAR). You wouldn't need the specify the `genome` argument then. The other option (perhaps the longer route) is to forge a BSgenome package from scratch - I am not familiar with the process but you can find more details [here](https://bioconductor.org/packages/release/bioc/vignettes/BSgenome/inst/doc/BSgenomeForge.pdf).

**Comment by houruiyan** [comment]
Hi Dr Chung,

Thank you very much for your response. Yes, I am trying to passing bam file. Now I am trying to forge a BSgenome package. 
Thank you!
