### ISSUE TITLE
create proActiv wrapper to return summarizedExperiment with promoter ranges

### ISSUE THREAD

**Issue by jonathangoeke** [GoekeLab/proActiv#6]
- create proActiv() wrapper to return summarizedExperiment with promoter ranges from input object and named file list

**Comment by jleechung** [comment]
Implemented with `proActiv`, which takes in two compulsory arguments:
- `files`: path of junction/BAM files as input
- `promoterAnnotation`: promoter annotation object

Returns a `summarizedExperiment` object, with promoter counts and activity as `assays`, gene expression stored as `metadata` and promoter-to-gene ID map in `rowData`.
